### ISSUE TITLE
How do you process your literate file?

### ISSUE THREAD

**Issue by paluh** [Thimoteus/simple-recursion#1]
I've noticed that this literate file has different format than one required by your `purescript-literate` processor. Am I right? How do you process it to `*.purs`?

**Comment by Thimoteus** [comment]
It should all be documented in the binary's `--help` flag, but this is what I do:

1. `rm -rf src/`
2. `litps compile --input literate/`

That'll generate the `.purs` files and run the compiler on them.

**Comment by paluh** [comment]
@Thimoteus thanks for clarification!
